praw-dev/asyncpraw

.github/workflows/ci.yml, .readthedocs.yml
=> Fix readthedocs errors

tests/integration/__init__.py, tests/unit/__init__.py, tests/unit/models/reddit/test_rules.py
Fixes some errors occurring with tests
=> Fix some errors with tests

CHANGES.rst
=> Add change log entry for #20

CHANGES.rst, asyncpraw/models/reddit/submission.py, tests/unit/models/reddit/test_submission.py
Cherry picked from praw-dev/praw:
* https://github.com/praw-dev/praw/pull/1560
=> Add support for gallery urls

CHANGES.rst, asyncpraw/endpoints.py, asyncpraw/models/__init__.py, asyncpraw/models/listing/listing.py, asyncpraw/models/reddit/subreddit.py, asyncpraw/objector.py, asyncpraw/reddit.py, tests/integration/cassettes/TestSubredditRelationships.test_moderator_invited_moderators.json, tests/integration/models/reddit/test_subreddit.py
Add invited moderators endpoint
(cherry picked from commit 4edfe71564856843e51b6e4f685b116ecaa1ba3a)
- https://github.com/praw-dev/praw/pull/1561
=> Add invited moderators endpoint

asyncpraw/praw.ini
(cherry picked from commit [3c02c430b41b0c8f5875c76eeb5dc27d23abece5](https://github.com/praw-dev/praw/commit/3c02c430b41b0c8f5875c76eeb5dc27d23abece5) & [aa8355f63a35c3aa70fdc3399341bdb57a637fdb](https://github.com/praw-dev/praw/commit/aa8355f63a35c3aa70fdc3399341bdb57a637fdb))
- https://github.com/praw-dev/praw/pull/1554
=> Make comment more descriptive

asyncpraw/models/comment_forest.py
(cherry picked from commit [2bf8cc18d4fe1518acfd6e4e652874dec33c7ee0](https://github.com/praw-dev/praw/commit/2bf8cc18d4fe1518acfd6e4e652874dec33c7ee0)
- https://github.com/praw-dev/praw/pull/1569
=> update CommentForest.list() signature

asyncpraw/models/reddit/subreddit.py
(cherry picked from commit [09d71ae266aee6139387965afb0e6a0ba4eb1952](https://github.com/praw-dev/praw/commit/09d71ae266aee6139387965afb0e6a0ba4eb1952))
- https://github.com/praw-dev/praw/pull/1566
=> Fix modmail stream doc

CHANGES.rst
=> Add changelog entry for Subreddits.gold -> Subreddits.premium rename

CHANGES.rst, asyncpraw/endpoints.py, asyncpraw/models/__init__.py, asyncpraw/models/reddit/inline_media.py, asyncpraw/models/reddit/subreddit.py, docs/code_overview/other.rst, docs/code_overview/other/inlinegif.rst, docs/code_overview/other/inlineimage.rst, docs/code_overview/other/inlinemedia.rst, docs/code_overview/other/inlinevideo.rst, tests/integration/cassettes/TestSubreddit.test_submit__selftext_inline_media.json, tests/integration/models/reddit/test_subreddit.py, tests/unit/models/reddit/test_inline_media.py, tests/unit/models/reddit/test_subreddit.py
(cherry picked from commit [6d9848e1006bee4cf437e4415d5d055674715ba3](https://github.com/praw-dev/praw/commit/6d9848e1006bee4cf437e4415d5d055674715ba3))
Fixes #27 
* https://github.com/praw-dev/praw/pull/1563
=> Add ability to submit selttext with inline media

CHANGES.rst, asyncpraw/models/reddit/subreddit.py
(cherry picked from commit 83323ef46f1ff17ec844b82fa5640a6cacbbc734)
- https://github.com/praw-dev/praw/pull/1542
=> Fix bug with leaving as a moderator when using token auth

asyncpraw/models/reddit/subreddit.py
(cherry picked from commit 4f9e9847effe1fead1c0a7b81ebdbc935624eb7a)
- https://github.com/praw-dev/praw/pull/1559
=> Update SubredditModeration.update documentation

asyncpraw/models/reddit/base.py, asyncpraw/models/reddit/collections.py, asyncpraw/models/reddit/comment.py, asyncpraw/models/reddit/live.py, asyncpraw/models/reddit/message.py, asyncpraw/models/reddit/modmail.py, asyncpraw/models/reddit/redditor.py, asyncpraw/models/reddit/removal_reasons.py, asyncpraw/models/reddit/rules.py, asyncpraw/models/reddit/submission.py, asyncpraw/models/reddit/subreddit.py, asyncpraw/models/reddit/wikipage.py, tests/unit/models/reddit/test_collections.py, tests/unit/models/reddit/test_comment.py, tests/unit/models/reddit/test_live.py, tests/unit/models/reddit/test_redditor.py, tests/unit/models/reddit/test_removal_reasons.py, tests/unit/models/reddit/test_rules.py, tests/unit/models/reddit/test_submission.py, tests/unit/models/reddit/test_subreddit.py, tests/unit/test_reddit.py
(cherry picked from commit a1f7e015a8a80c08ef70069d341e45bd74f9145e)
- https://github.com/praw-dev/praw/pull/1585
=> Implement a check on RedditBase for unset STR_FIELD attribute values

asyncpraw/models/reddit/subreddit.py
(cherry picked from commit 742e61001e5eafbdd72eca5d8ace0f925c954533)
- https://github.com/praw-dev/praw/pull/1572
=> Updated documentation for modmail conversation (#1572)

CHANGES.rst
(cherry picked from commit 08444f7c52b5b7a4e49ce3c11b463a80d0eb8907)
- https://github.com/praw-dev/praw/pull/1592
=> Add change log entry for #1563

asyncpraw/models/reddit/base.py, tests/unit/models/reddit/test_base.py
=> Make RedditBase deepcopy actually deepcopy

AUTHORS.rst, asyncpraw/models/reddit/comment.py, asyncpraw/models/reddit/submission.py
(cherry picked from commit b912277d9a868c801e4f9f8805e7489ab8a45caf)
- https://github.com/praw-dev/praw/pull/1608
=> Add saved attribute to docs for comment and submission models (#1608)

asyncpraw/models/reddit/message.py
(cherry picked from commit e1b22c802c1d132a0d973dcca285410332f7da01)
- https://github.com/praw-dev/praw/pull/1535
=> docs: add body_html to doc strings..update AUTHORS.rst [#1495]

asyncpraw/models/preferences.py
(cherry picked from commit 351af3989393cb83f1a6e05efcf7fde3effde5f5)
- https://github.com/praw-dev/praw/pull/1661
=> Update user preferences table

asyncpraw/reddit.py
- https://github.com/praw-dev/praw/pull/1674
=> Rename parameter in Reddit.info.generator and actually use parameter instead of one from outer scope

setup.py
- https://github.com/praw-dev/praw/pull/1678
=> Add project urls

docs/conf.py
- https://github.com/praw-dev/praw/pull/1677
=> Update sphinx config

asyncpraw/models/mod_action.py, docs/code_overview/other.rst, docs/code_overview/other/mod_action.rst
- https://github.com/praw-dev/praw/pull/1681
=> Add the ModAction class to the docs

docs/code_overview/other.rst, docs/code_overview/other/stylesheet.rst
- https://github.com/praw-dev/praw/pull/1682
=> Add the Stylesheet class to the docs

asyncpraw/models/reddit/subreddit.py
- https://github.com/praw-dev/praw/pull/1680
=> Subreddit update

CHANGES.rst, asyncpraw/models/user.py
This just adds in changes that were missed from #78.
- https://github.com/praw-dev/praw/pull/1684
=> Finish doc changes to me()

asyncpraw/models/reddit/comment.py
- https://github.com/praw-dev/praw/pull/1685
=> Fix typo in comment.show docs

.pre-commit-config.yaml
- https://github.com/praw-dev/praw/pull/1686
=> Update pre-commit revision line to be an actual tag

CHANGES.rst, asyncpraw/config.py, asyncpraw/models/auth.py, asyncpraw/reddit.py, asyncpraw/util/token_manager.py, docs/code_overview/other.rst, docs/code_overview/other/token_manager.rst, docs/examples/lmgtfy_bot.py, docs/examples/obtain_refresh_token.py, docs/examples/use_file_token_manager.py, docs/getting_started/authentication.rst, docs/getting_started/configuration/options.rst, docs/tutorials/refresh_token.rst, setup.py, tests/conftest.py, tests/integration/__init__.py, tests/unit/test_deprecations.py, tests/unit/test_reddit.py, tests/unit/util/test_token_manager.py
- https://github.com/praw-dev/praw/pull/1687
=> Support single-use refresh tokens

asyncpraw/util/token_manager.py, tests/unit/test_reddit.py, tests/unit/util/test_token_manager.py
- https://github.com/praw-dev/praw/pull/1693
=> Use the ABC class to declare an abstract class

CHANGES.rst, asyncpraw/models/__init__.py, asyncpraw/models/list/moderated.py, asyncpraw/models/reddit/redditor.py, asyncpraw/objector.py, asyncpraw/reddit.py, docs/code_overview/other.rst, docs/code_overview/other/moderatedlist.rst
(cherry picked from commit ab5eef4fd913684a8d10da51bf8996ebd8848354)
- https://github.com/praw-dev/praw/pull/1703
=> Make Redditor.moderated utilized all data returned from the API

tests/unit/models/reddit/test_collections.py, tests/unit/models/reddit/test_removal_reasons.py, tests/unit/util/test_token_manager.py
=> Cleanup some tests

AUTHORS.rst, asyncpraw/models/reddit/submission.py
(cherry picked from commit 83d078df48cf7400067d85548da800412001e6ed)
- https://github.com/praw-dev/praw/pull/1702
=> Link flair template

asyncpraw/models/reddit/subreddit.py
(cherry picked from commit 8b44b8fb0d200f91565a141eb24d990fcd78bba1)
- https://github.com/praw-dev/praw/pull/1705
=> Add join_requests to docs

CHANGES.rst, asyncpraw/models/__init__.py, asyncpraw/models/reddit/redditor.py, asyncpraw/models/reddit/subreddit.py, asyncpraw/models/reddit/user_subreddit.py, docs/code_overview/other.rst, docs/code_overview/other/usersubreddit.rst, docs/code_overview/other/usersubredditmoderation.rst, tests/integration/cassettes/TestUserSubredditModeration.test_accept_invite__no_invite.json, tests/integration/cassettes/TestUserSubredditModeration.test_update.json, tests/integration/models/reddit/test_user_subreddit.py, tests/unit/test_deprecations.py
(cherry picked from commit 28c75ce012dda7415f67bf8d6581c50e93ea3886)
https://github.com/praw-dev/praw/pull/1707
=> Objectify user subreddit

CHANGES.rst, asyncpraw/models/reddit/subreddit.py
(cherry picked from commit 97b933935377fbb304c0275312a3e382a3fd540b)
https://github.com/praw-dev/praw/pull/1713
=> Add deprecation warning for legacy modmail

CHANGES.rst, asyncpraw/exceptions.py, asyncpraw/reddit.py, tests/integration/cassettes/TestWikiPage.test_content_md__invalid_name.json, tests/integration/models/reddit/test_wikipage.py
(cherry picked from commit fa24684ae40335cbfe2c487d4b885b1f21e24f1b)
https://github.com/praw-dev/praw/pull/1715
=> Handle more Bad Requests

pre_push.py, pyproject.toml
=> Exclude paths that start with .venv from pre_push checks

CHANGES.rst, asyncpraw/models/reddit/mixins/fullname.py, docs/code_overview/other.rst, docs/code_overview/other/fullnamemixin.rst, tests/integration/cassettes/TestUser.test_blocked_fullname.json, tests/integration/models/test_user.py
(cherry picked from commit dc29bbb179d8a05809cb98f18765e61d9916fe70)
- https://github.com/praw-dev/praw/pull/1734
=> Fix bug in FullnameMix.fullname

CHANGES.rst, asyncpraw/models/reddit/redditor.py, tests/integration/cassettes/TestRedditor.test_block.json, tests/integration/models/reddit/test_redditor.py
(cherry picked from commit c55cc62093110db575eed4f99b642d379ae60a87)
- https://github.com/praw-dev/praw/pull/1736
=> Modify Redditor.block

CHANGES.rst, asyncpraw/endpoints.py, asyncpraw/objector.py, asyncpraw/reddit.py, tests/integration/cassettes/TestReddit.test_username_available__available.json, tests/integration/cassettes/TestReddit.test_username_available__unavailable.json, tests/integration/cassettes/TestReddit.test_username_available_exception.json, tests/integration/test_reddit.py
(cherry picked from commit fc8c2dcd18bdeced5bc03a82050ffa656b048cb2)
- https://github.com/praw-dev/praw/pull/1729
=> Add oauth endpoint username_available

asyncpraw/models/comment_forest.py
(cherry picked from commit dd7563a60f9c27c08004b19d9a66b363b19d3dfd)
- https://github.com/praw-dev/praw/pull/1737
=> Add warning about use of morechildren endpoint

setup.py
(cherry picked from commit df8ec64fbe8120ac2fc134e1861c8b19c16256b4)
- https://github.com/praw-dev/praw/pull/1738
=> Depend on at least asyncprawcore 2.1

CHANGES.rst, asyncpraw/util/token_manager.py, docs/examples/use_sqlite_token_manager.py, docs/tutorials/refresh_token.rst, setup.py, tests/unit/util/test_token_manager.py
(cherry picked from commit bb0e0070a89b2e801e691a7161074d83378bd81a)
- https://github.com/praw-dev/praw/pull/1692
=> Add SQLite3TokenManager and associated example

.github/workflows/set_active_versions.yml, tools/set_active_docs.py
(cherry picked from commit 2a92aef95af7079f70fd8c4812fa86e9c814d352)
- https://github.com/praw-dev/praw/pull/1698
=> Add set_active_docs.py to set what versions are visible

CHANGES.rst, tools/set_version.py
(cherry picked from commit 7f1392dcae25179463f7becf475a55342fcf07fd)
- https://github.com/praw-dev/praw/pull/1741
=> Add semantic versioning link to changelog

AUTHORS.rst, asyncpraw/models/reddit/redditor.py
(cherry picked from commit 02530bcf4e70d9b11af140e5ccc8b3b46145cd98)
- https://github.com/praw-dev/praw/pull/1675
=> Added submissions to attribute list in docs

AUTHORS.rst, docs/getting_started/quick_start.rst
(cherry picked from commit 44ebf9e5a71c167aa01c40a934fa946a5f010c1e)
- https://github.com/praw-dev/praw/pull/1739
=> Removed passive aggressive tone from quick start guide

docs/conf.py, setup.py
=> Fix bullets on readthedocs

CHANGES.rst, asyncpraw/endpoints.py, asyncpraw/models/reddit/wikipage.py, docs/code_overview/other.rst, tests/integration/cassettes/TestWikiPage.test_discussions.json, tests/integration/cassettes/TestWikiPageModeration.test_revert.json, tests/integration/cassettes/TestWikiPageModeration.test_revert_css_fail.json, tests/integration/models/reddit/test_wikipage.py
(cherry picked from commit da9ea5971d46e1f461ad9ce6519acd5d1b1c61dd)
- https://github.com/praw-dev/praw/pull/1751
=> Add WikiPage.discussions and WikiPageModeration.revert

CHANGES.rst, asyncpraw/endpoints.py, asyncpraw/models/reddit/submission.py, tests/integration/cassettes/TestSubmissionModeration.test_update_crowd_control_level.json, tests/integration/models/reddit/test_submission.py
(cherry picked from commit ada285c2e494873aa77a655c3a108817a3d01d94)
- https://github.com/praw-dev/praw/pull/1753
=> Add SubmissionModeration.update_crowd_control_level

CHANGES.rst, asyncpraw/config.py, asyncpraw/models/reddit/submission.py, docs/getting_started/configuration/options.rst, tests/unit/models/reddit/test_submission.py
Sync with praw/master after https://github.com/praw-dev/praw/pull/1775
=> Print warning when comment_sort is set after fetch

CHANGES.rst, asyncpraw/models/reddit/subreddit.py, tests/integration/cassettes/TestSubredditLinkFlairTemplates.test_user_selectable.json, tests/integration/models/reddit/test_subreddit.py
(cherry picked from commit d697ef6eeba15ba3643473485c3dfc9e162f72a0)
- https://github.com/praw-dev/praw/pull/1776
=> Add new function for getting list of flair templates

.github/workflows/ci.yml
Pulling changes from https://github.com/praw-dev/praw/pull/1772 into asyncpraw
=> Bugfix/coveralls GitHub action updated (#1772)

CHANGES.rst, asyncpraw/reddit.py, docs/getting_started/configuration/options.rst, tests/unit/test_reddit.py
(cherry picked from commit praw-dev/praw@bb0e00810511980154972ab143e42dfbe2695700)
- https://github.com/praw-dev/praw/pull/1780
=> Improvements to automated RATELIMIT handling

asyncpraw/models/reddit/subreddit.py
(cherry picked from commit praw-dev/praw@7caae013b0e26ead088790461c81270173fd25ad)
- https://github.com/praw-dev/praw/pull/1785
=> Fix code example typo

.github/workflows/pre-commit_autoupdate.yml
(cherry picked from commit praw-dev/praw@78cf99e41495c27bb7a8306faf02298b36ddc94b)
- https://github.com/praw-dev/praw/pull/1787
=> Fix pre-commit auto update workflow

CHANGES.rst, asyncpraw/util/token_manager.py
(cherry picked from commit praw-dev/praw@de1caeeb2f911ec590ae1e902c1201f117a4059f)
- https://github.com/praw-dev/praw/pull/1788
=> Only import sqlite3 in SQLiteTokenManager class

docs/getting_started/configuration/prawini.rst
(cherry picked from commit praw-dev/praw@01737f77f309575fec85e4a7539ff063b75c679d)
- https://github.com/praw-dev/praw/pull/1790
=> Clarify that example sensitive values aren't valid

asyncpraw/models/reddit/submission.py
(cherry picked from commit praw-dev/praw@c3e7092c4cee08b407fc4c80cbf5d0d30d6838a4)
- https://github.com/praw-dev/praw/pull/1797
=> Fix grammar in Submission.sticky docstring

CHANGES.rst, asyncpraw/endpoints.py, asyncpraw/models/__init__.py, asyncpraw/models/helpers.py, asyncpraw/models/list/draft.py, asyncpraw/models/reddit/draft.py, asyncpraw/models/reddit/subreddit.py, asyncpraw/objector.py, asyncpraw/reddit.py, docs/code_overview/asyncpraw_models.rst, docs/code_overview/models/draft.rst, docs/code_overview/other.rst, docs/code_overview/other/draftlist.rst, docs/code_overview/other/usersubreddit.rst, docs/code_overview/reddit/drafts.rst, docs/code_overview/reddit_instance.rst, tests/integration/cassettes/TestDraft.test_create.json, tests/integration/cassettes/TestDraft.test_delete.json, tests/integration/cassettes/TestDraft.test_fetch.json, tests/integration/cassettes/TestDraft.test_list.json, tests/integration/cassettes/TestDraft.test_submit.json, tests/integration/cassettes/TestDraft.test_submit__different_subreddit.json, tests/integration/cassettes/TestDraft.test_submit__different_title.json, tests/integration/cassettes/TestDraft.test_update.json, tests/integration/models/reddit/test_draft.py, tests/unit/models/reddit/test_draft.py
(cherry picked from commit praw-dev/praw@2c487023d95b9cd601f09430ccda1f9d2123fec5)
- https://github.com/praw-dev/praw/pull/1763
=> Add support for drafts

setup.py
=> Add aiohttp requirement

AUTHORS.rst, CHANGES.rst, asyncpraw/models/user.py, tests/integration/cassettes/TestUser.test_pin.json, tests/integration/cassettes/TestUser.test_pin__comment.json, tests/integration/cassettes/TestUser.test_pin__deleted_submission.json, tests/integration/cassettes/TestUser.test_pin__empty_slot.json, tests/integration/cassettes/TestUser.test_pin__ignore_conflicts.json, tests/integration/cassettes/TestUser.test_pin__invalid_num.json, tests/integration/cassettes/TestUser.test_pin__num.json, tests/integration/cassettes/TestUser.test_pin__remove.json, tests/integration/cassettes/TestUser.test_pin__remove_num.json, tests/integration/cassettes/TestUser.test_pin__removed_submission.json, tests/integration/cassettes/TestUser.test_pin__replace_slot.json, tests/integration/models/test_user.py
(cherry picked from commit 35090c863c0386ae1ce5515e3abc546beaa3ac97)
- https://github.com/praw-dev/praw/pull/1799
=> Add ability to pin submissions to user's profile

.github/workflows/ci.yml, CHANGES.rst, README.rst, docs/getting_started/configuration/prawini.rst, docs/getting_started/installation.rst, docs/getting_started/quick_start.rst, setup.py
(cherry picked from commit d4517409b8f43a7bc1b8ad603daeead00a40c0f6)
- https://github.com/praw-dev/praw/pull/1822
=> Drop support for Python 3.6

AUTHORS.rst, CHANGES.rst, asyncpraw/endpoints.py, asyncpraw/models/reddit/collections.py, tests/integration/cassettes/TestCollectionModeration.test_update_display_layout__empty_string.json, tests/integration/cassettes/TestCollectionModeration.test_update_display_layout__gallery.json, tests/integration/cassettes/TestCollectionModeration.test_update_display_layout__invalid_layout.json, tests/integration/cassettes/TestCollectionModeration.test_update_display_layout__lowercase.json, tests/integration/cassettes/TestCollectionModeration.test_update_display_layout__none.json, tests/integration/cassettes/TestCollectionModeration.test_update_display_layout__timeline.json, tests/integration/models/reddit/test_collections.py
(cherry picked from commit praw-dev/praw@f49d37380bb68fb033c02634e4600be98d71934f)
- https://github.com/praw-dev/praw/pull/1829
=> Add support to update the display layout of posts in collections

docs/getting_started/configuration/options.rst, docs/getting_started/ratelimits.rst, docs/index.rst
(cherry picked from commit praw-dev/praw@cc08a645a21ef9da343eb359ca4cb2f4f19040ce)
- https://github.com/praw-dev/praw/pull/1794
=> Add clarification for `ratelimit_seconds`

.github/workflows/ci.yml
=> Skip docstrfmt in CI

asyncpraw/models/reddit/widgets.py
(cherry picked from commit praw-dev/praw@0b5724f419f999afa38690e7ef18941f12bc5f0e)
- https://github.com/praw-dev/praw/pull/1835
=> Add typing annotations to widgets.py

AUTHORS.rst, asyncpraw/models/user.py
=> await missing in example

asyncpraw/models/user.py
=> await missing in example 

asyncpraw/models/reddit/mixins/__init__.py
(cherry picked from commit praw-dev/praw@fb3441a5c0bc050364a4687baf1a2a7fec966c39)
- https://github.com/praw-dev/praw/pull/1836
=> Add typing annotations to reddit/models/mixins/__init__.py

asyncpraw/models/reddit/redditor.py, asyncpraw/models/reddit/wikipage.py
(cherry picked from commit praw-dev/praw@b009cbfa54fc115777a4ff70eb9b3bcee33a683f)
=> Missed documentation cleanup

.github/CONTRIBUTING.rst, docs/package_info/contributing.rst
This adds more info for getting started with contributing to Async PRAW
=> Improve contributing docs

docs/tutorials/refresh_token.rst
(cherry picked from commit praw-dev/praw@490f139981e2f5a5ce62e7abe55be7d7500df4a1)
- https://github.com/praw-dev/praw/pull/1852
=> Fix &amp; error

asyncpraw/models/reddit/subreddit.py, asyncpraw/models/reddit/user_subreddit.py
Added The Missing Attribute in Subreddit class's docs.
=> update the docs of Subreddit's attributes

CHANGES.rst, asyncpraw/objector.py
(cherry picked from commit praw-dev/praw@3172943413a7e14e1071ab8fd03699b17cc632c7)
- https://github.com/praw-dev/praw/pull/1873
=> Don't pre-populate ModmailConversation.messages

asyncpraw/models/reddit/subreddit.py
(cherry picked from commit praw-dev/praw@56d8a33424c60fb1a2c0a6f54fb35e061c5e7c90)
- https://github.com/praw-dev/praw/pull/1874
=> Fix typo in docs

asyncpraw/models/listing/mixins/redditor.py, asyncpraw/models/reddit/live.py, asyncpraw/models/reddit/mixins/gildable.py, asyncpraw/models/reddit/mixins/replyable.py
(cherry picked from commit praw-dev/praw@b3acd111ab39f00b8ea52e81877ee4f0eab88383)
- https://github.com/praw-dev/praw/pull/1875
=> Add missing typing annotations and improve docs

asyncpraw/objector.py
(cherry picked from commit https://github.com/praw-dev/praw/commit/1fd5bc207716cf4e4549fdc92b38ef8b1f61a775)
- https://github.com/praw-dev/praw/pull/1877
=> Don't set obj_ids since it can be missing data

asyncpraw/reddit.py
(cherry picked from commit praw-dev/praw@35da17b1ff422e50d639f44b5faba5bd164b18b0)
- https://github.com/praw-dev/praw/pull/1879
=> Add int to **config_settings type annotation

AUTHORS.rst, asyncpraw/models/reddit/subreddit.py
(cherry picked from commit praw-dev/praw@44230d15a392cd529d3bee1c71391dc5446494e4)
- https://github.com/praw-dev/praw/pull/1888
=> Added targeted harassment prevention note

docs/_static/theme_override.css
(cherry picked from commit praw-dev/praw@8720d503a2f0a7184485eada572ec51f6209fd56)
- https://github.com/praw-dev/praw/pull/1889
=> Dark mode CSS improvements

CHANGES.rst, asyncpraw/models/reddit/subreddit.py, tests/integration/cassettes/TestSubredditStylesheet.test_delete_mobile_banner.json, tests/integration/cassettes/TestSubredditStylesheet.test_upload_mobile_banner__jpg.json, tests/integration/cassettes/TestSubredditStylesheet.test_upload_mobile_banner__png.json, tests/integration/models/reddit/test_subreddit.py
(cherry picked from commit praw-dev/praw@61d4132b9feed55b5f0c380a8738f721ae2b1812)
- https://github.com/praw-dev/praw/pull/1902
=> Added support for Mobile Banner uploads. (#1902)

.github/workflows/ci.yml, setup.py
This pull request adds support for Python 3.11
=> Add support for Python 3.11

CHANGES.rst, asyncpraw/const.py
Reverts praw-dev/asyncpraw#236
=> Revert "Release v7.7.0"

asyncpraw/models/comment_forest.py
(cherry picked from commit praw-dev/praw@e955f30503d70b111fe46803831c2e85ba68d379)
- https://github.com/praw-dev/praw/pull/1932
=> CommentForest: replace_more typing

CHANGES.rst, asyncpraw/models/reddit/removal_reasons.py, tests/integration/models/reddit/test_removal_reasons.py
(cherry picked from commit praw-dev/praw@2a438fd67725fc62cea564a50a5f9c6df5f813d7)
- https://github.com/praw-dev/praw/pull/1934
=> Fix removal reason ordering

asyncpraw/models/reddit/subreddit.py
(cherry picked from commit praw-dev/praw@89c0402103ac82b725ad000af1f1187c9a19a22d)
- https://github.com/praw-dev/praw/pull/1935
=> Fix docs for muted

docs/getting_started/authentication.rst
(cherry picked from commit praw-dev/praw@d21875009572c4082114848d536f667d213d344f)
=> Update link to old reddit

setup.py
=> Pin vcrpy to 4.2.1

CHANGES.rst, asyncpraw/models/reddit/modmail.py, tests/integration/cassettes/TestModmailConversation.test_reply__internal.json, tests/integration/models/reddit/test_modmail.py
(cherry picked from commit praw-dev/praw@5984516aa37a09c858c61dbbeda584adc9fd6c1d)
- https://github.com/praw-dev/praw/pull/1960
=> Fix modmail reply bug

asyncpraw/models/reddit/subreddit.py, tests/integration/models/reddit/test_subreddit.py
=> Fix xml parsing on error

tests/integration/models/reddit/test_widgets.py
(cherry picked from commit praw-dev/praw@72f10ca64e4d7afb471f959a2b7e4439c9b6429e)
- https://github.com/praw-dev/praw/pull/1969
=> Fix flake8 complaint

CHANGES.rst, asyncpraw/endpoints.py, asyncpraw/models/reddit/subreddit.py, asyncpraw/reddit.py, tests/integration/cassettes/TestSubredditFlairTemplates.test_reorder.json, tests/integration/cassettes/TestSubredditLinkFlairTemplates.test_reorder.json, tests/integration/models/reddit/test_subreddit.py
(cherry picked from commit praw-dev/praw@32eefbf6e2f25983a1c72f5d88d6d0def884e75a)
- https://github.com/praw-dev/praw/commit/32eefbf6e2f25983a1c72f5d88d6d0def884e75a
=> Added support for reordering flairs through reddit.flair.reorder

CHANGES.rst, README.rst, docs/getting_started/installation.rst, docs/getting_started/quick_start.rst, pyproject.toml, tests/integration/models/reddit/test_subreddit.py, tests/unit/models/reddit/test_subreddit.py, tests/unit/models/test_redditors.py, tests/unit/test_config.py, tests/unit/test_reddit.py, tests/unit/util/test_token_manager.py, tox.ini
(cherry picked from commit praw-dev/praw@9c49551401ec85f628af8ef0bae79f1d7a81e202)
- https://github.com/praw-dev/praw/pull/1976
=> Drop support for Python 3.7

CHANGES.rst, asyncpraw/models/reddit/redditor.py, asyncpraw/objector.py, asyncpraw/reddit.py, tests/integration/cassettes/TestComment.test_resolve_from_share_url.json, tests/integration/cassettes/TestComment.test_resolve_from_share_url__invalid_url.json, tests/integration/cassettes/TestSubmission.test_resolve_from_share_url.json, tests/integration/cassettes/TestSubmission.test_resolve_from_share_url__invalid_url.json, tests/integration/models/reddit/test_comment.py, tests/integration/models/reddit/test_submission.py
(cherry picked from commit praw-dev/praw@61dfa9fb47f61ccef124e1773a9f7d43742053da)
- https://github.com/praw-dev/praw/pull/1994
=> Add support for new share link

docs/code_overview/reddit/drafts.rst
(cherry picked from commit praw-dev/praw@8b61fdff626a7c55ad1a73ba3295ba8b49f5abc0)
- https://github.com/praw-dev/praw/pull/1986
=> Fix title in drafts.rst

asyncpraw/models/reddit/mixins/inboxtoggleable.py
(cherry picked from commit praw-dev/praw@a0736f1e50e7f15a3a95850b726ad38ff28f3328)
- https://github.com/praw-dev/praw/pull/1990
=> Add more explicit description about the `sendreplies` methods

CHANGES.rst, asyncpraw/config.py, asyncpraw/models/auth.py, asyncpraw/reddit.py, docs/getting_started/configuration/options.rst, docs/getting_started/logging.rst
CR fixes
(cherry picked from commit praw-dev/praw@ba1b87d76cf721c6a52f1500bab28ab51d3a0575)
Fix another test
(cherry picked from commit praw-dev/praw@bf79ea2046d186f7729c6201b2fd9ef0b00841d4)
Fix a test
(cherry picked from commit praw-dev/praw@b8ee8e6f87ed97d09728333a43e0902f3ba19a90)
How about this
(cherry picked from commit praw-dev/praw@1c4590b08a66f0bee4d6d8c1758d4381684a6c28)
Add to changelog
(cherry picked from commit praw-dev/praw@12ee566c646e15bac362fa506f7bf9caad2ff805)
Update logging docs
(cherry picked from commit praw-dev/praw@e4bb2ec49a8694c019f193957263c295cc28ac52)
Add doc note here
(cherry picked from commit praw-dev/praw@77101333591a6b1cb5034e1c171c599ab9adc595)
Fix black
(cherry picked from commit praw-dev/praw@c5fa92e95df369f30b9f0914a708ab15663e3fed)
Bare bones …
=> Add support for window size config

.github/CONTRIBUTING.rst, .github/workflows/scorecard.yml, .github/workflows/tag_release.yml, README.rst, docs/code_overview/exceptions.rst, docs/getting_started/installation.rst, docs/package_info/contributing.rst
(cherry picked from commit praw-dev/praw@3ef5a4fe8b8d26b75a52238f6ca9a50b9f85cc2a)
- https://github.com/praw-dev/praw/pull/2048
=> Update references of master branch to main branch
